/**
 * ELO-Tiered Tactical Drill Library
 * Based on "A Statistical Analysis of Tactical Motif Probability in Chess"
 *
 * Key Findings:
 * - ELO 800-900: Fork, Skewer (most common blunders)
 * - ELO 1400: Deflection, X-Ray Attack
 * - ELO 1600: Trapped Piece
 * - "Big 4" Most Frequent: Fork, Hanging Piece, Discovered Attack, Pin
 *
 * Progressive time limits enforce "flash recognition":
 * - Beginner (800): 8 seconds
 * - Intermediate (1200): 6 seconds
 * - Advanced (1600): 5 seconds
 * - Expert (1800): 4 seconds
 * - Master (2000+): 3 seconds
 */

import type { ELORating } from '../types';

export type TacticalMotif =
  | 'fork'
  | 'hanging-piece'
  | 'pin'
  | 'discovered-attack'
  | 'skewer'
  | 'back-rank-mate'
  | 'double-attack'
  | 'deflection'
  | 'x-ray'
  | 'trapped-piece'
  | 'removing-defender'
  | 'greek-gift'
  | 'zwischenzug'
  | 'desperado'
  | 'smothered-mate'
  | 'attraction'
  | 'clearance'
  | 'interference';

export interface TacticalDrill {
  id: string;
  name: string;
  fen: string;
  solution: string; // SAN notation
  solutionSquare: string; // Target square (e.g., "h7" for destination-based matching)
  motif: TacticalMotif;
  eloRating: ELORating;
  timeLimit: number; // Seconds - STRICT enforcement
  hint: string;
  explanation: string;
  frequency: 'very-high' | 'high' | 'medium' | 'low'; // Based on Lichess data
}

/**
 * ===== ELO 800: BEGINNER DRILLS =====
 * Focus: "Big 4" basics - Fork, Hanging Piece, Pin, Discovered Attack
 * Time Limit: 8 seconds
 * Statistical Priority: These are the MOST COMMON tactical blunders
 */

export const DRILLS_800: TacticalDrill[] = [
  // FORK - Highest frequency tactic (20,514 occurrences in Lichess data)
  {
    id: '800-fork-1',
    name: 'Knight Fork - King and Rook',
    fen: '4k3/8/8/8/3N4/8/4r3/4K3 w - - 0 1',
    solution: 'Nf5',
    solutionSquare: 'f5',
    motif: 'fork',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Your knight can attack two pieces at once.',
    explanation:
      'Nf5 forks the king and rook. This is THE most common tactic in chess - you must see it instantly!',
    frequency: 'very-high',
  },
  {
    id: '800-fork-2',
    name: 'Pawn Fork',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2BnP3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'd3',
    solutionSquare: 'd3',
    motif: 'fork',
    eloRating: 800,
    timeLimit: 8,
    hint: 'A pawn can fork two pieces.',
    explanation: 'd3 forks the bishop and knight! Never underestimate pawn forks.',
    frequency: 'very-high',
  },
  {
    id: '800-fork-3',
    name: 'Queen Fork',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Qa4',
    solutionSquare: 'a4',
    motif: 'fork',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Your queen can attack the king and another piece.',
    explanation:
      'Qa4 pins the knight to the king and threatens to win it. Queen forks are powerful!',
    frequency: 'very-high',
  },

  // HANGING PIECE - #3 most frequent (8,307 occurrences)
  {
    id: '800-hanging-1',
    name: 'Undefended Knight',
    fen: 'rnbqkb1r/pppp1ppp/5n2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'hanging-piece',
    eloRating: 800,
    timeLimit: 8,
    hint: "One of Black's pieces is completely undefended.",
    explanation: 'Nxe5 wins the hanging pawn for free. Always check: "What\'s undefended?"',
    frequency: 'very-high',
  },
  {
    id: '800-hanging-2',
    name: 'Hanging Rook',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/3P1N2/PPP2PPP/RNBQKB1R b KQkq - 0 1',
    solution: 'Nxe4',
    solutionSquare: 'e4',
    motif: 'hanging-piece',
    eloRating: 800,
    timeLimit: 8,
    hint: 'White left a piece undefended.',
    explanation:
      'Nxe4 captures the hanging pawn. The most common blunder is leaving pieces en prise!',
    frequency: 'very-high',
  },

  // PIN - #6 most frequent (6,299 occurrences)
  {
    id: '800-pin-1',
    name: 'Simple Pin to King',
    fen: 'rnbqkb1r/pppp1ppp/5n2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Bb5',
    solutionSquare: 'b5',
    motif: 'pin',
    eloRating: 800,
    timeLimit: 8,
    hint: 'You can pin a knight to the king.',
    explanation:
      'Bb5 pins the knight to the king. The knight cannot move without exposing the king to check.',
    frequency: 'very-high',
  },
  {
    id: '800-pin-2',
    name: 'Pin to Queen',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 0 1',
    solution: 'Bg5',
    solutionSquare: 'g5',
    motif: 'pin',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Pin the knight to the queen.',
    explanation: 'Bg5 pins the f6 knight to the queen on d8. Pins are everywhere!',
    frequency: 'very-high',
  },

  // SKEWER - Peak frequency at 800-900 ELO
  {
    id: '800-skewer-1',
    name: 'Rook Skewer',
    fen: '6k1/5ppp/8/3K4/8/8/8/3R4 w - - 0 1',
    solution: 'Rd8+',
    solutionSquare: 'd8',
    motif: 'skewer',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Check the king, then win material.',
    explanation: 'Rd8+ skewers the king. After Kf7/Kg7, the rook on d8 is yours.',
    frequency: 'high',
  },
  {
    id: '800-skewer-2',
    name: 'Bishop Skewer',
    fen: 'r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1',
    solution: 'Ra8+',
    solutionSquare: 'a8',
    motif: 'skewer',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Your rook can check and win material.',
    explanation: 'Ra8+ skewers king and rook. Always check for skewers on open lines!',
    frequency: 'high',
  },

  // DISCOVERED ATTACK - #4 most frequent (8,110 occurrences)
  {
    id: '800-discovered-1',
    name: 'Basic Discovered Attack',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'discovered-attack',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Moving your knight will unveil an attack.',
    explanation: 'Nxe5 discovers an attack on f7 from your Bc4. Double threats win games!',
    frequency: 'very-high',
  },

  // Additional FORKS for pattern recognition
  {
    id: '800-fork-4',
    name: 'Bishop Fork - Two Rooks',
    fen: 'r3k2r/8/8/3B4/8/8/8/4K3 w kq - 0 1',
    solution: 'Ba8',
    solutionSquare: 'a8',
    motif: 'fork',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Your bishop can attack both rooks.',
    explanation: 'Ba8 forks both rooks on a8 and h8. Black must lose material!',
    frequency: 'very-high',
  },
  {
    id: '800-fork-5',
    name: 'Knight Fork - Queen and Bishop',
    fen: 'r1bqkb1r/pppp1ppp/2n5/8/3nP3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 0 1',
    solution: 'Nxd4',
    solutionSquare: 'd4',
    motif: 'fork',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Capture the knight and create a fork.',
    explanation: 'After Nxd4, the knight forks queen and bishop. Knights are forking machines!',
    frequency: 'very-high',
  },

  // Additional HANGING PIECES
  {
    id: '800-hanging-3',
    name: 'Hanging Queen',
    fen: 'rnb1kbnr/pppp1ppp/8/4p3/4P2q/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Nxh4',
    solutionSquare: 'h4',
    motif: 'hanging-piece',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Black left the queen undefended!',
    explanation: 'Nxh4 wins the queen! Always check if your opponent left pieces hanging.',
    frequency: 'very-high',
  },
  {
    id: '800-hanging-4',
    name: 'Undefended Bishop',
    fen: 'rnbqk2r/pppp1ppp/5n2/2b1p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Nxc5',
    solutionSquare: 'c5',
    motif: 'hanging-piece',
    eloRating: 800,
    timeLimit: 8,
    hint: 'The bishop on c5 has no protection.',
    explanation: 'Nxc5 captures the hanging bishop. Scan for undefended pieces every move!',
    frequency: 'very-high',
  },

  // Additional PINS
  {
    id: '800-pin-3',
    name: 'Rook Pin',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Bb5',
    solutionSquare: 'b5',
    motif: 'pin',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Pin the knight to the king.',
    explanation: 'Bb5 pins the c6 knight to the king. The knight is now paralyzed!',
    frequency: 'very-high',
  },
  {
    id: '800-pin-4',
    name: 'Pin and Win',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'pin',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Capture the pinned pawn with check.',
    explanation:
      "Bxf7+ wins the pinned pawn. The f7 pawn couldn't move because it would expose the king!",
    frequency: 'very-high',
  },

  // DOUBLE ATTACK variations
  {
    id: '800-double-1',
    name: 'Queen Double Attack',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Qe2',
    solutionSquare: 'e2',
    motif: 'double-attack',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Your queen can attack two targets at once.',
    explanation:
      'Qe2 attacks both the e5 pawn and sets up threats. Double attacks force tough choices!',
    frequency: 'high',
  },
  {
    id: '800-double-2',
    name: 'Rook Double Attack',
    fen: '4k3/8/8/3r4/8/2P1P3/8/4K3 b - - 0 1',
    solution: 'Rd3',
    solutionSquare: 'd3',
    motif: 'double-attack',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Attack both pawns at once.',
    explanation: 'Rd3 attacks both the c3 and e3 pawns. One of them must fall!',
    frequency: 'high',
  },

  // BACK RANK MATE threats
  {
    id: '800-backrank-1',
    name: 'Back Rank Mate',
    fen: '6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1',
    solution: 'Ra8#',
    solutionSquare: 'a8',
    motif: 'back-rank-mate',
    eloRating: 800,
    timeLimit: 8,
    hint: 'The king has no escape squares.',
    explanation:
      'Ra8# is checkmate! The king is trapped by its own pawns. Always give your king breathing room!',
    frequency: 'high',
  },
  {
    id: '800-backrank-2',
    name: 'Back Rank Weakness',
    fen: 'r4rk1/5ppp/8/8/8/8/5PPP/R4RK1 w - - 0 1',
    solution: 'Ra8',
    solutionSquare: 'a8',
    motif: 'back-rank-mate',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Invade the back rank.',
    explanation:
      'Ra8 forces Rxa8 Rxa8#. Back rank mates are deadly - always watch your first rank!',
    frequency: 'high',
  },

  // BATCH 2: Additional beginner patterns (21-40)
  // More FORK drills
  {
    id: '800-fork-6',
    name: 'Rook Fork - Two Pieces',
    fen: '4k3/8/2b1n3/8/8/8/3R4/4K3 w - - 0 1',
    solution: 'Rd6',
    solutionSquare: 'd6',
    motif: 'fork',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Your rook can attack both pieces.',
    explanation: 'Rd6 forks the bishop and knight. Rooks can fork too!',
    frequency: 'very-high',
  },
  {
    id: '800-fork-7',
    name: 'Simple Queen Fork',
    fen: 'r1b1kb1r/pppp1ppp/2n5/4p3/2B1n3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Qd5',
    solutionSquare: 'd5',
    motif: 'fork',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Queen forks are powerful.',
    explanation: 'Qd5 forks the knight on e4 and threatens f7. Queen mobility wins!',
    frequency: 'very-high',
  },
  {
    id: '800-fork-8',
    name: 'Knight Fork - Classic',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Ng5',
    solutionSquare: 'g5',
    motif: 'fork',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Attack f7 which is weak.',
    explanation: 'Ng5 attacks f7 and threatens the rook. Weak squares are targets!',
    frequency: 'very-high',
  },

  // More HANGING PIECE drills
  {
    id: '800-hanging-5',
    name: 'Undefended Rook',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R b KQkq - 0 1',
    solution: 'Nxe4',
    solutionSquare: 'e4',
    motif: 'hanging-piece',
    eloRating: 800,
    timeLimit: 8,
    hint: 'The e4 pawn is hanging.',
    explanation: 'Nxe4 wins the undefended pawn. Always check what&apos;s hanging!',
    frequency: 'very-high',
  },
  {
    id: '800-hanging-6',
    name: 'Capturing Hanging Bishop',
    fen: 'rnbqk2r/pppp1ppp/5n2/2b1p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'hanging-piece',
    eloRating: 800,
    timeLimit: 8,
    hint: 'The e5 pawn has no defender.',
    explanation: 'Nxe5 captures the hanging pawn. Free material!',
    frequency: 'very-high',
  },

  // More PIN drills
  {
    id: '800-pin-5',
    name: 'Queen Pin',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'pin',
    eloRating: 800,
    timeLimit: 8,
    hint: 'The f7 pawn is pinned.',
    explanation: 'Bxf7+ wins the pinned pawn with check. Pins immobilize!',
    frequency: 'very-high',
  },
  {
    id: '800-pin-6',
    name: 'Rook Pin to Queen',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQR1K1 b kq - 0 1',
    solution: 'Nf6',
    solutionSquare: 'f6',
    motif: 'pin',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Develop and prepare to exploit the pin.',
    explanation: 'Nf6 develops while the pin remains. Understanding pins is crucial!',
    frequency: 'very-high',
  },

  // More DISCOVERED ATTACK drills
  {
    id: '800-discovered-2',
    name: 'Discovered Attack on Queen',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'discovered-attack',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Move the knight to discover attack.',
    explanation: 'Nxe5 discovers attack on the queen from your queen. Double threats!',
    frequency: 'very-high',
  },
  {
    id: '800-discovered-3',
    name: 'Simple Discovered Check',
    fen: 'rnbqk2r/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'discovered-attack',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Discover check on the king.',
    explanation: 'Nxe5+ discovers check from the bishop. Discovered checks are forcing!',
    frequency: 'very-high',
  },

  // More SKEWER drills
  {
    id: '800-skewer-3',
    name: 'Queen Skewer',
    fen: '4k3/8/8/3q4/8/8/4Q3/4K3 w - - 0 1',
    solution: 'Qe8+',
    solutionSquare: 'e8',
    motif: 'skewer',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Check the king, win the queen.',
    explanation: 'Qe8+! skewers king and queen. The king moves, queen falls!',
    frequency: 'high',
  },
  {
    id: '800-skewer-4',
    name: 'Bishop Skewer Pattern',
    fen: '4k3/8/8/8/8/8/1r6/1B2K3 w - - 0 1',
    solution: 'Ba2',
    solutionSquare: 'a2',
    motif: 'skewer',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Check and win material.',
    explanation: 'Ba2+ skewers king and rook. Skewers attack the more valuable piece first!',
    frequency: 'high',
  },

  // More DOUBLE ATTACK drills
  {
    id: '800-double-3',
    name: 'Bishop Double Attack',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'double-attack',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Check and win material.',
    explanation: 'Bxf7+ checks the king and wins the f7 pawn. Double attack with check!',
    frequency: 'high',
  },
  {
    id: '800-double-4',
    name: 'Knight Double Attack',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'double-attack',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Centralize the knight.',
    explanation: 'Nd5 attacks multiple pieces from the center. Knights love central squares!',
    frequency: 'high',
  },

  // More BACK RANK drills
  {
    id: '800-backrank-3',
    name: 'Back Rank Defense',
    fen: 'r4r1k/5ppp/8/8/8/8/5PPP/R4RK1 w - - 0 1',
    solution: 'Rf8+',
    solutionSquare: 'f8',
    motif: 'back-rank-mate',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Force the trade on the back rank.',
    explanation: 'Rf8+! forces Rxf8 Rxf8#. Back rank tactics win games!',
    frequency: 'high',
  },
  {
    id: '800-backrank-4',
    name: 'Simple Back Rank Mate',
    fen: '5rk1/5ppp/8/8/8/8/5PPP/5RK1 w - - 0 1',
    solution: 'Rf8#',
    solutionSquare: 'f8',
    motif: 'back-rank-mate',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Deliver checkmate.',
    explanation: 'Rf8# is mate! The king has no flight squares. h3 would have prevented this!',
    frequency: 'high',
  },

  // Additional basic tactics
  {
    id: '800-tactic-1',
    name: 'Removing Defender Basic',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'removing-defender',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Remove the defender of the knight.',
    explanation: 'Nxe5! If Nxe5 then Bxf7+ wins. Removing defenders creates tactics!',
    frequency: 'high',
  },
  {
    id: '800-tactic-2',
    name: 'Simple Checkmate Pattern',
    fen: 'r1bqkb1r/pppp1Qpp/2n2n2/4p3/2B1P3/8/PPPP1PPP/RNB1K2R b KQkq - 0 1',
    solution: 'Qxf7#',
    solutionSquare: 'f7',
    motif: 'attraction',
    eloRating: 800,
    timeLimit: 8,
    hint: 'The king is trapped.',
    explanation: 'Scholars Mate pattern! Always develop pieces and castle early!',
    frequency: 'high',
  },
  {
    id: '800-tactic-3',
    name: 'Material Win',
    fen: 'rnbqkb1r/pppp1ppp/5n2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'hanging-piece',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Free pawn!',
    explanation: 'Nxe5 wins the hanging pawn. In the opening, protect your pawns!',
    frequency: 'very-high',
  },
  {
    id: '800-tactic-4',
    name: 'Fork and Win',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Ng5',
    solutionSquare: 'g5',
    motif: 'fork',
    eloRating: 800,
    timeLimit: 8,
    hint: 'Attack the weak f7 square.',
    explanation: 'Ng5 attacks f7 with two pieces. f7 is the weakest square early!',
    frequency: 'very-high',
  },
];

/**
 * ===== ELO 1000-1200: INTERMEDIATE DRILLS =====
 * Focus: "Big 4" variations + Back Rank + Double Attack
 * Time Limit: 6 seconds
 * Must solve 800-level drills in < 8 seconds before unlocking
 */

export const DRILLS_1200: TacticalDrill[] = [
  // More complex FORKS
  {
    id: '1200-fork-1',
    name: 'Knight Fork - Queen and Rook',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 0 1',
    solution: 'Nd4',
    solutionSquare: 'd4',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Your knight can fork the queen and bishop.',
    explanation: 'Nd4 forks queen on d1 and bishop on c4. Calculate this instantly!',
    frequency: 'very-high',
  },
  {
    id: '1200-fork-2',
    name: 'Bishop Fork (Royalty Fork)',
    fen: 'r2qkb1r/ppp2ppp/2n5/3pPb2/3Pn3/2N1BN2/PPP2PPP/R2QKB1R b KQkq - 0 1',
    solution: 'Bb4',
    solutionSquare: 'b4',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Your bishop can attack king and knight.',
    explanation: 'Bb4+ forks king and knight on c3. Bishops fork too!',
    frequency: 'high',
  },

  // DISCOVERED ATTACK variations
  {
    id: '1200-discovered-1',
    name: 'Discovered Check',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'discovered-attack',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Your knight move will discover check.',
    explanation: 'Nxe5 discovers check from Bc4. Discovered checks are forcing!',
    frequency: 'very-high',
  },

  // BACK RANK MATE
  {
    id: '1200-backrank-1',
    name: 'Classic Back Rank',
    fen: '6k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1',
    solution: 'Rd8#',
    solutionSquare: 'd8',
    motif: 'back-rank-mate',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'The king is trapped by its own pawns.',
    explanation: 'Rd8# is mate! Back rank weaknesses are fatal.',
    frequency: 'high',
  },
  {
    id: '1200-backrank-2',
    name: 'Back Rank Threat',
    fen: '2r3k1/5ppp/8/8/8/8/5PPP/2R3K1 w - - 0 1',
    solution: 'Rxc8#',
    solutionSquare: 'c8',
    motif: 'back-rank-mate',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Trade rooks with check.',
    explanation: 'Rxc8# is checkmate. Always watch your back rank!',
    frequency: 'high',
  },

  // DOUBLE ATTACK
  {
    id: '1200-double-1',
    name: 'Queen Double Attack',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Qa4',
    solutionSquare: 'a4',
    motif: 'double-attack',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Your queen can attack two pieces.',
    explanation: 'Qa4 pins the c6 knight and threatens the e5 pawn.',
    frequency: 'high',
  },

  // More complex PINS
  {
    id: '1200-pin-1',
    name: 'Exploiting a Pin',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Ng5',
    solutionSquare: 'g5',
    motif: 'pin',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Attack f7, which is pinned.',
    explanation: 'Ng5 attacks f7, which cannot move due to the pin. Exploit pins!',
    frequency: 'very-high',
  },

  // Additional complex FORKS
  {
    id: '1200-fork-3',
    name: 'Queen Fork - Royalty',
    fen: 'r2qkb1r/ppp2ppp/2n5/3pPb2/3Pn3/2N1BN2/PPP2PPP/R2Q1RK1 b kq - 0 1',
    solution: 'Nf2',
    solutionSquare: 'f2',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Your knight can fork king and queen.',
    explanation: 'Nf2+ forks the king and queen. The royal fork is devastating!',
    frequency: 'high',
  },
  {
    id: '1200-fork-4',
    name: 'Rook Fork',
    fen: '4k3/8/8/2q1n3/8/8/3R4/4K3 w - - 0 1',
    solution: 'Rd5',
    solutionSquare: 'd5',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Your rook can attack both pieces.',
    explanation: 'Rd5 forks the queen and knight. Even rooks fork!',
    frequency: 'high',
  },

  // SKEWER variations
  {
    id: '1200-skewer-1',
    name: 'Bishop Skewer',
    fen: '4k3/8/8/8/8/8/1q6/KB6 w - - 0 1',
    solution: 'Bb7',
    solutionSquare: 'b7',
    motif: 'skewer',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Check the king first, then win the queen.',
    explanation: 'Bb7+ skewers king and queen. The king moves, the queen falls!',
    frequency: 'high',
  },
  {
    id: '1200-skewer-2',
    name: 'Queen Skewer',
    fen: 'r3k2r/8/8/8/8/8/8/4Q3 w kq - 0 1',
    solution: 'Qe8+',
    solutionSquare: 'e8',
    motif: 'skewer',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Skewer the king and rook.',
    explanation: 'Qe8+ forces Kd7 or Kf7, then Qxh8 wins the rook.',
    frequency: 'high',
  },

  // DISCOVERED ATTACK variations
  {
    id: '1200-discovered-2',
    name: 'Discovered Attack - Win Queen',
    fen: 'r2qkb1r/ppp2ppp/2n5/3pPb2/3Pn3/2N1BN2/PPP2PPP/R2QKB1R w KQkq - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'discovered-attack',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Capture with discovered attack on queen.',
    explanation: 'Nxd5 discovers attack on the queen while winning a pawn!',
    frequency: 'very-high',
  },
  {
    id: '1200-discovered-3',
    name: 'Discovered Check Pattern',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'discovered-attack',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Discover check while winning material.',
    explanation: 'Nxe5+ discovers check from your bishop and wins the e5 pawn!',
    frequency: 'very-high',
  },

  // Additional HANGING PIECES
  {
    id: '1200-hanging-1',
    name: 'Overworked Defender',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/2NP1N2/PPP2PPP/R1BQKB1R b KQkq - 0 1',
    solution: 'Nxe4',
    solutionSquare: 'e4',
    motif: 'hanging-piece',
    eloRating: 1200,
    timeLimit: 6,
    hint: "The e4 pawn looks defended but isn't.",
    explanation: 'Nxe4! If dxe4 then Qxd1. The d3 pawn was overworked defending both!',
    frequency: 'very-high',
  },
  {
    id: '1200-hanging-2',
    name: 'Tactical Sequence',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'hanging-piece',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Sacrifice to win material.',
    explanation: 'Bxf7+! After Kxf7, the knight on c6 is hanging. Look for tactical sequences!',
    frequency: 'high',
  },

  // Additional PINS
  {
    id: '1200-pin-2',
    name: 'Breaking the Pin',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b KQkq - 0 1',
    solution: 'd5',
    solutionSquare: 'd5',
    motif: 'pin',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Break the pin and attack the bishop.',
    explanation: 'd5 breaks the pin and attacks the bishop. Sometimes you can counter-attack!',
    frequency: 'high',
  },
  {
    id: '1200-pin-3',
    name: 'Absolute Pin Exploitation',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2BnP3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'pin',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'The knight on d4 is pinned to the king.',
    explanation:
      'Nxe5 is safe because the d4 knight is absolutely pinned and can&apos;t recapture!',
    frequency: 'very-high',
  },

  // REMOVING DEFENDER
  {
    id: '1200-removing-1',
    name: 'Remove the Defender',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Nxc6',
    solutionSquare: 'c6',
    motif: 'removing-defender',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Remove the defender of e5.',
    explanation: 'Nxc6 removes the defender. After bxc6, Nxe5 wins the pawn!',
    frequency: 'high',
  },

  // Additional BACK RANK patterns
  {
    id: '1200-backrank-3',
    name: 'Back Rank Tactics',
    fen: '3r2k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1',
    solution: 'Rd8+',
    solutionSquare: 'd8',
    motif: 'back-rank-mate',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Trade into back rank mate.',
    explanation: 'Rd8+! forces Rxd8 then your rook delivers mate. Back rank awareness!',
    frequency: 'high',
  },
  {
    id: '1200-double-2',
    name: 'Rook Double Attack',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/2NP1N2/PPP2PPP/R1BQKB1R b KQkq - 0 1',
    solution: 'Bb4',
    solutionSquare: 'b4',
    motif: 'double-attack',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Attack knight and threaten king.',
    explanation: 'Bb4 pins the knight and threatens the king. Dual purpose move!',
    frequency: 'high',
  },

  // BATCH 2: Intermediate tactical patterns (21-40)
  {
    id: '1200-fork-5',
    name: 'Multi-Target Fork',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N2N2/PPP2PPP/R1BQKB1R w KQ - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Centralize with threats.',
    explanation: 'Nd5! attacks f6, threatens multiple pieces. Central dominance!',
    frequency: 'high',
  },
  {
    id: '1200-fork-6',
    name: 'Pawn Fork Advanced',
    fen: 'rnbqkb1r/ppp2ppp/3p1n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: 'd4',
    solutionSquare: 'd4',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Pawn forks are powerful.',
    explanation: 'd4! forks bishop and knight. Never underestimate pawns!',
    frequency: 'high',
  },
  {
    id: '1200-discovered-4',
    name: 'Discovered Double Attack',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'discovered-attack',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Discover and attack.',
    explanation: 'Nxe5! discovers attack while capturing. Multi-purpose moves!',
    frequency: 'very-high',
  },
  {
    id: '1200-pin-4',
    name: 'Pin Mastery',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bg5',
    solutionSquare: 'g5',
    motif: 'pin',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Pin the knight.',
    explanation: 'Bg5! pins f6 knight to queen. Pressure builds!',
    frequency: 'very-high',
  },
  {
    id: '1200-skewer-3',
    name: 'Advanced Skewer',
    fen: '4k3/8/8/3r4/8/8/3R4/4K3 w - - 0 1',
    solution: 'Rd8+',
    solutionSquare: 'd8',
    motif: 'skewer',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Force the king to move.',
    explanation: 'Rd8+! skewers king and rook. Classic pattern!',
    frequency: 'high',
  },
  {
    id: '1200-hanging-3',
    name: 'Multiple Hanging Pieces',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/2NP1N2/PPP2PPP/R1BQKB1R b KQkq - 0 1',
    solution: 'Nxe4',
    solutionSquare: 'e4',
    motif: 'hanging-piece',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'The e4 pawn lacks protection.',
    explanation: 'Nxe4! wins material. Always scan for hanging pieces!',
    frequency: 'very-high',
  },
  {
    id: '1200-double-3',
    name: 'Double Threat Pattern',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'double-attack',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Create multiple threats.',
    explanation: 'Nd5! threatens Nxf6+ and Nxc7. Multiple threats win!',
    frequency: 'high',
  },
  {
    id: '1200-removing-2',
    name: 'Deflect the Guardian',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'removing-defender',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Remove key defender.',
    explanation: 'Bxf7+! After Kxf7, knight on c6 hangs. Forcing sequences!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-1',
    name: 'Tactical Sequence',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b kq - 0 1',
    solution: 'Nxe4',
    solutionSquare: 'e4',
    motif: 'hanging-piece',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Calculate the sequence.',
    explanation: 'Nxe4! If dxe4 then Qxd1. Overloaded defender!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-2',
    name: 'Breakthrough Tactic',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w kq - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Central breakthrough.',
    explanation: 'Nd5! attacks c7 and f6. Centralization is key!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-3',
    name: 'Pin Exploitation',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bg5',
    solutionSquare: 'g5',
    motif: 'pin',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Pin and pressure.',
    explanation: 'Bg5! increases pressure on pinned knight. Build up attacks!',
    frequency: 'very-high',
  },
  {
    id: '1200-tactic-4',
    name: 'Material Exchange',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'hanging-piece',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Calculate the trade.',
    explanation: 'Nxe5! wins pawn. After Nxe5, Bxf7+ regains piece with advantage!',
    frequency: 'high',
  },
  {
    id: '1200-backrank-4',
    name: 'Back Rank Combo',
    fen: '2r3k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1',
    solution: 'Rd8+',
    solutionSquare: 'd8',
    motif: 'back-rank-mate',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Force the rook trade.',
    explanation: 'Rd8+! Rxd8 is forced, then recapture delivers mate!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-5',
    name: 'Weak Square',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Ng5',
    solutionSquare: 'g5',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Attack the weakness.',
    explanation: 'Ng5! targets f7. Weak squares are goldmines!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-6',
    name: 'Piece Activity',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b kq - 0 1',
    solution: 'Bg4',
    solutionSquare: 'g4',
    motif: 'pin',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Activate with purpose.',
    explanation: 'Bg4! pins knight and increases piece activity. Active pieces!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-7',
    name: 'Development Advantage',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w kq - 0 1',
    solution: 'Bg5',
    solutionSquare: 'g5',
    motif: 'pin',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Use development edge.',
    explanation: 'Bg5! exploits better development. Piece coordination matters!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-8',
    name: 'Central Control',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'd4',
    solutionSquare: 'd4',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Break the center.',
    explanation: 'd4! opens lines and gains space. Center is crucial!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-9',
    name: 'Piece Coordination',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Coordinate pieces.',
    explanation: 'Nd5! centralizes with threats. Piece harmony wins games!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-10',
    name: 'Forcing Move',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'removing-defender',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Force the issue.',
    explanation: 'Bxf7+! forcing king move, winning material. Forcing moves control tempo!',
    frequency: 'high',
  },
  {
    id: '1200-tactic-11',
    name: 'Tactical Vision',
    fen: 'r1bqk02r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w kq - 0 1',
    solution: 'Ng5',
    solutionSquare: 'g5',
    motif: 'fork',
    eloRating: 1200,
    timeLimit: 6,
    hint: 'Spot the tactic.',
    explanation: 'Ng5! attacks h7 and f7. Sharp tactical vision needed!',
    frequency: 'high',
  },
];

/**
 * ===== ELO 1400-1600: ADVANCED DRILLS =====
 * Focus: Deflection, X-Ray, Trapped Piece, Removing Defender
 * Time Limit: 5 seconds
 * Peak complexity for this ELO range per research
 */

export const DRILLS_1400: TacticalDrill[] = [
  // DEFLECTION - Peak at 1400 ELO
  {
    id: '1400-deflection-1',
    name: 'Deflect the Defender',
    fen: 'r2qkb1r/ppp2ppp/2n2n2/3pPb2/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1',
    solution: 'exf6',
    solutionSquare: 'f6',
    motif: 'deflection',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Deflect the f7 pawn from defending the king.',
    explanation: 'exf6 deflects the defense. After gxf6 or Qxf6, lines open for attack.',
    frequency: 'high',
  },
  {
    id: '1400-deflection-2',
    name: 'Queen Deflection',
    fen: 'r2q1rk1/ppp2ppp/2n5/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Qd3',
    solutionSquare: 'd3',
    motif: 'deflection',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Force the queen away from defending.',
    explanation: 'Qd3 deflects the queen from defending the bishop on f5.',
    frequency: 'high',
  },

  // X-RAY ATTACK - Peak at 1400 ELO
  {
    id: '1400-xray-1',
    name: 'X-Ray Attack on King',
    fen: 'r4rk1/ppp2ppp/2n5/8/1b1P4/2N1Q3/PPP2PPP/R1B2RK1 w - - 0 1',
    solution: 'Qe8',
    solutionSquare: 'e8',
    motif: 'x-ray',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Your queen can x-ray through the rook.',
    explanation: 'Qe8! pins the rook via x-ray. X-rays see through pieces!',
    frequency: 'medium',
  },

  // TRAPPED PIECE - Peak at 1600 ELO
  {
    id: '1400-trapped-3',
    name: 'Trapped Bishop',
    fen: 'rnbqkb1r/pp1p1ppp/4pn2/2p5/2PP4/5N2/PP2PPPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Qa4+',
    solutionSquare: 'a4',
    motif: 'trapped-piece',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'The bishop has no good squares.',
    explanation: 'Qa4+ and the bishop on c8 is trapped after Nc6.',
    frequency: 'medium',
  },
  {
    id: '1400-trapped-4',
    name: 'Trapped Knight',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2BnP3/5N2/PPPP1PPP/RNBQK2R b KQkq - 0 1',
    solution: 'c6',
    solutionSquare: 'c6',
    motif: 'trapped-piece',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Trap the bishop with pawns.',
    explanation: "c6 and b5 trap the bishop. Noah's Ark Trap pattern!",
    frequency: 'medium',
  },

  // REMOVING DEFENDER
  {
    id: '1400-removing-1',
    name: 'Remove the Key Defender',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b5/2BpP3/5N2/PPP2PPP/RNBQ1RK1 w kq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'removing-defender',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'The king defends a critical piece.',
    explanation: 'Bxf7+ removes the defender of d4. After Kxf7 Nxd4, material won.',
    frequency: 'medium',
  },

  // Additional DEFLECTION patterns
  {
    id: '1400-deflection-3',
    name: 'Rook Deflection',
    fen: 'r4rk1/ppp2ppp/2n5/3q4/3P4/2N1Q3/PPP2PPP/R4RK1 w - - 0 1',
    solution: 'Qe8',
    solutionSquare: 'e8',
    motif: 'deflection',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Deflect the rook from the back rank.',
    explanation: 'Qe8! deflects the rook. If Rxe8 then Rxe8#. Deflection wins!',
    frequency: 'high',
  },
  {
    id: '1400-deflection-4',
    name: 'Bishop Deflection',
    fen: 'r2qkb1r/ppp2ppp/2n5/3pPb2/3P4/2N1BN2/PPP2PPP/R2QKB1R b KQkq - 0 1',
    solution: 'Bxe3',
    solutionSquare: 'e3',
    motif: 'deflection',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Deflect the defender of d5.',
    explanation: 'Bxe3! deflects the knight. After fxe3, the d4 pawn falls.',
    frequency: 'high',
  },

  // Additional X-RAY patterns
  {
    id: '1400-xray-2',
    name: 'X-Ray on Queen',
    fen: 'r1bq1rk1/ppp2ppp/2n5/3pPb2/3P4/2N1Q3/PPP2PPP/R1B2RK1 b - - 0 1',
    solution: 'Bxc3',
    solutionSquare: 'c3',
    motif: 'x-ray',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'X-ray through the knight to the queen.',
    explanation: 'Bxc3! If Qxc3, then the queen is x-rayed by the bishop on c8.',
    frequency: 'medium',
  },
  {
    id: '1400-xray-3',
    name: 'Rook X-Ray',
    fen: '4r1k1/ppp2ppp/8/3q4/3P4/2Q5/PPP2PPP/4R1K1 w - - 0 1',
    solution: 'Re8+',
    solutionSquare: 'e8',
    motif: 'x-ray',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'X-ray check through the rook.',
    explanation: 'Re8+! forces Rxe8, and the king is in check via x-ray.',
    frequency: 'medium',
  },

  // Additional TRAPPED PIECE patterns
  {
    id: '1400-trapped-1',
    name: 'Trapped Queen',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 0 1',
    solution: 'Qa5+',
    solutionSquare: 'a5',
    motif: 'trapped-piece',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'The queen will be trapped after check.',
    explanation: 'Qa5+ and the queen has no safe square. Tactical awareness!',
    frequency: 'medium',
  },
  {
    id: '1400-trapped-2',
    name: 'Trapped Rook',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 0 1',
    solution: 'Bg5',
    solutionSquare: 'g5',
    motif: 'trapped-piece',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Pin and trap the knight.',
    explanation: 'Bg5 pins the knight. After h6, Bxf6 traps the knight on h5.',
    frequency: 'medium',
  },

  // Additional REMOVING DEFENDER patterns
  {
    id: '1400-removing-2',
    name: 'Sacrifice to Remove',
    fen: 'r2qkb1r/ppp2ppp/2n2n2/3pPb2/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'removing-defender',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Remove the pawn defending e6.',
    explanation: 'Nxd5! removes the defender. After Nxd5 exf6, material advantage.',
    frequency: 'high',
  },
  {
    id: '1400-removing-3',
    name: 'Clearance Sacrifice',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'removing-defender',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Remove the defender of f6.',
    explanation: 'Nd5 attacks f6 and threatens Nxf6+ winning material.',
    frequency: 'high',
  },

  // Complex FORKS
  {
    id: '1400-fork-1',
    name: 'Complex Knight Fork',
    fen: 'r2qkb1r/ppp2ppp/2n2n2/3pPb2/3P4/2N2N2/PPP2PPP/R1BQKB1R b KQkq - 0 1',
    solution: 'Ne4',
    solutionSquare: 'e4',
    motif: 'fork',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Fork with tempo.',
    explanation: 'Ne4 forks queen and c3 knight with threats. Multi-purpose moves!',
    frequency: 'high',
  },
  {
    id: '1400-fork-2',
    name: 'Queen Fork Pattern',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Qa4',
    solutionSquare: 'a4',
    motif: 'fork',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Fork bishop and knight.',
    explanation: 'Qa4 pins the c6 knight and attacks the c5 bishop. Double attack!',
    frequency: 'high',
  },

  // SKEWER patterns
  {
    id: '1400-skewer-1',
    name: 'Tactical Skewer',
    fen: '4k3/8/8/3r4/8/8/3Q4/4K3 w - - 0 1',
    solution: 'Qd8+',
    solutionSquare: 'd8',
    motif: 'skewer',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Check and win the rook.',
    explanation: 'Qd8+ skewers king and rook. The reverse pin!',
    frequency: 'high',
  },
  {
    id: '1400-skewer-2',
    name: 'Bishop Skewer Pattern',
    fen: '4k3/8/8/8/8/8/1r6/KB6 w - - 0 1',
    solution: 'Bb7+',
    solutionSquare: 'b7',
    motif: 'skewer',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Skewer king and rook.',
    explanation: 'Bb7+ forces Kd7 or Kf7, then Bxb2 wins the rook.',
    frequency: 'high',
  },

  // DISCOVERED ATTACK patterns
  {
    id: '1400-discovered-1',
    name: 'Discovered Attack with Capture',
    fen: 'r2qkb1r/ppp2ppp/2n2n2/3pPb2/3P4/2N1BN2/PPP2PPP/R2QKB1R w KQkq - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'discovered-attack',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Discover attack on the bishop.',
    explanation: 'Nxd5 discovers attack on f5 bishop from your bishop on e3!',
    frequency: 'very-high',
  },

  // Additional PIN exploitation
  {
    id: '1400-pin-1',
    name: 'Breaking Through Pin',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'pin',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'The pin can be broken tactically.',
    explanation: 'Bxf7+! breaks through despite appearing pinned. Calculate variations!',
    frequency: 'high',
  },

  // BATCH 2: Advanced intermediate patterns (21-40)
  {
    id: '1400-clearance-1',
    name: 'Clearance Sacrifice',
    fen: 'r2qkb1r/ppp2ppp/2n2n2/3pPb2/3P4/2N2N2/PPP1QPPP/R1B1KB1R w KQkq - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'clearance',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Clear the path for attack.',
    explanation: 'Nxd5! clears e-file for rook. Clearance creates tactical opportunities!',
    frequency: 'medium',
  },
  {
    id: '1400-interference-1',
    name: 'Interference Pattern',
    fen: 'r2qkb1r/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQkq - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'interference',
    eloRating: 1400,
    timeLimit: 5,
    hint: "Block the defender's line.",
    explanation: 'Nd5 interferes with the defense of f6. Blocking wins material!',
    frequency: 'low',
  },
  {
    id: '1400-double-4',
    name: 'Double Attack Mastery',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b KQkq - 0 1',
    solution: 'Ng4',
    solutionSquare: 'g4',
    motif: 'double-attack',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Attack two targets at once.',
    explanation: 'Ng4! attacks f2 and threatens h2. Double attacks overwhelm defenses!',
    frequency: 'high',
  },
  {
    id: '1400-deflection-5',
    name: 'Deflection Combo',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Qb3',
    solutionSquare: 'b3',
    motif: 'deflection',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Deflect the f7 pawn.',
    explanation: 'Qb3! deflects defense of f7. Multi-purpose queen moves win!',
    frequency: 'high',
  },
  {
    id: '1400-fork-3',
    name: 'Royal Fork Pattern',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R b KQkq - 0 1',
    solution: 'Nd4',
    solutionSquare: 'd4',
    motif: 'fork',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Fork multiple pieces.',
    explanation: 'Nd4! forks queen and bishop. Knights excel at forking!',
    frequency: 'high',
  },
  {
    id: '1400-pin-2',
    name: 'Pin to Win Material',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b KQkq - 0 1',
    solution: 'Qa5',
    solutionSquare: 'a5',
    motif: 'pin',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Pin the knight to the king.',
    explanation: 'Qa5! pins c3 knight to king. Absolute pins are devastating!',
    frequency: 'very-high',
  },
  {
    id: '1400-skewer-3',
    name: 'Skewer Sequence',
    fen: '2kr3r/ppp2ppp/2n5/3q4/3P4/2Q5/PPP2PPP/2KR3R w - - 0 1',
    solution: 'Qc8+',
    solutionSquare: 'c8',
    motif: 'skewer',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Skewer king and rook.',
    explanation: 'Qc8+! forces Kxc8 Rxh8+. Skewer sequences win material!',
    frequency: 'high',
  },
  {
    id: '1400-xray-4',
    name: 'X-Ray Threat',
    fen: 'r1bq1rk1/ppp2ppp/2n5/3pPb2/1b1P4/2N1Q3/PPP2PPP/R1B2RK1 w - - 0 1',
    solution: 'Qe4',
    solutionSquare: 'e4',
    motif: 'x-ray',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'X-ray through to the rook.',
    explanation: 'Qe4! threatens x-ray on f5 bishop and a8 rook. Long-range power!',
    frequency: 'medium',
  },
  {
    id: '1400-removing-4',
    name: 'Remove Guard Tactic',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Nxe5',
    solutionSquare: 'e5',
    motif: 'removing-defender',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Remove the defender of c5.',
    explanation: 'Nxe5! After Nxe5, Bxc5 wins material. Remove then capture!',
    frequency: 'high',
  },
  {
    id: '1400-trapped-5',
    name: 'Trap the Piece',
    fen: 'rnbqkb1r/pppp1ppp/5n2/4p3/4P3/3P1N2/PPP2PPP/RNBQKB1R b KQkq - 0 1',
    solution: 'Ng4',
    solutionSquare: 'g4',
    motif: 'trapped-piece',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Attack and limit squares.',
    explanation: 'Ng4! threatens f2. After h3, the knight retreats with tempo.',
    frequency: 'medium',
  },
  {
    id: '1400-discovered-2',
    name: 'Discovered Check Pattern',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b KQkq - 0 1',
    solution: 'Nd4',
    solutionSquare: 'd4',
    motif: 'discovered-attack',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Discover attack on the bishop.',
    explanation: 'Nd4! discovers attack from c5 bishop to c4 bishop. Discovery wins!',
    frequency: 'very-high',
  },
  {
    id: '1400-deflection-6',
    name: 'Deflect and Conquer',
    fen: 'r2q1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Qb3',
    solutionSquare: 'b3',
    motif: 'deflection',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Deflect from defending f7.',
    explanation: 'Qb3! deflects king from defending f7. Deflection creates weaknesses!',
    frequency: 'high',
  },
  {
    id: '1400-fork-4',
    name: 'Bishop Fork',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bb5',
    solutionSquare: 'b5',
    motif: 'fork',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Fork with the bishop.',
    explanation: 'Bb5! pins c6 knight and attacks c5 bishop. Bishops fork too!',
    frequency: 'high',
  },
  {
    id: '1400-double-5',
    name: 'Queen Double Attack',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Qa4',
    solutionSquare: 'a4',
    motif: 'double-attack',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Attack two undefended pieces.',
    explanation: 'Qa4! attacks both c6 knight and c5 bishop. Double attack wins!',
    frequency: 'high',
  },
  {
    id: '1400-pin-3',
    name: 'Exploit the Pin',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 b kq - 0 1',
    solution: 'Bg4',
    solutionSquare: 'g4',
    motif: 'pin',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Pin the knight to the queen.',
    explanation: 'Bg4! pins f3 knight to d1 queen. Pinned pieces are weak!',
    frequency: 'very-high',
  },
  {
    id: '1400-skewer-4',
    name: 'Rook Skewer Advanced',
    fen: '4k3/8/8/3q4/8/8/3R4/4K3 w - - 0 1',
    solution: 'Rd8+',
    solutionSquare: 'd8',
    motif: 'skewer',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Check and win the queen.',
    explanation: 'Rd8+! skewers king and queen. Forcing moves control the game!',
    frequency: 'high',
  },
  {
    id: '1400-xray-5',
    name: 'X-Ray Defense',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R b KQ - 0 1',
    solution: 'Re8',
    solutionSquare: 'e8',
    motif: 'x-ray',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'X-ray the e-file.',
    explanation: 'Re8! x-rays through e5 pawn to white pieces. X-ray defense!',
    frequency: 'medium',
  },
  {
    id: '1400-removing-5',
    name: 'Sacrifice Defender',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'removing-defender',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Remove the key defender.',
    explanation: 'Bxf7+! Kxf7 and the king is exposed. Removing key pieces wins!',
    frequency: 'high',
  },
  {
    id: '1400-discovered-3',
    name: 'Discovered Double',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b KQkq - 0 1',
    solution: 'Nxe4',
    solutionSquare: 'e4',
    motif: 'discovered-attack',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Discover and attack.',
    explanation: 'Nxe4! discovers bishop attack on c4 bishop while capturing. Double duty!',
    frequency: 'very-high',
  },
  {
    id: '1400-clearance-2',
    name: 'Clear the Line',
    fen: 'r2qkb1r/ppp2ppp/2n2n2/3pPb2/1b1P4/2N2N2/PPP1QPPP/R1B1KB1R w KQkq - 0 1',
    solution: 'exf6',
    solutionSquare: 'f6',
    motif: 'clearance',
    eloRating: 1400,
    timeLimit: 5,
    hint: 'Clear the e-file.',
    explanation: 'exf6! opens e-file for rook. Clearance unleashes piece power!',
    frequency: 'medium',
  },
];

/**
 * ===== ELO 1800-2000: EXPERT DRILLS =====
 * Focus: Multi-step tactics, Zwischenzug, Greek Gift, Desperado
 * Time Limit: 4 seconds
 * Requires deep pattern recognition
 */

export const DRILLS_1800: TacticalDrill[] = [
  // GREEK GIFT SACRIFICE
  {
    id: '1800-greek-1',
    name: 'Greek Gift Sacrifice',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3p4/1b1P4/2NBPN2/PPP2PPP/R1BQK2R w KQ - 0 1',
    solution: 'Bxh7+',
    solutionSquare: 'h7',
    motif: 'greek-gift',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Sacrifice on h7 to expose the king.',
    explanation: 'Bxh7+! Kxh7 Ng5+ and White wins the queen or delivers mate.',
    frequency: 'medium',
  },

  // ZWISCHENZUG (In-between move)
  {
    id: '1800-zwischenzug-1',
    name: 'In-Between Move',
    fen: 'r1bqk2r/ppp2ppp/2n5/3pPb2/1b1Pn3/2N2N2/PPP1QPPP/R1B1KB1R w KQkq - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'zwischenzug',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Before recapturing, create a bigger threat.',
    explanation: 'Nxd5! threatens Nc7+ before dealing with e4. Zwischenzug wins material!',
    frequency: 'low',
  },

  // DESPERADO
  {
    id: '1800-desperado-1',
    name: 'Desperado Rook',
    fen: '2r3k1/5ppp/8/3R4/8/2P5/5PPP/6K1 w - - 0 1',
    solution: 'Rxc8+',
    solutionSquare: 'c8',
    motif: 'desperado',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Your rook is doomed - cause maximum damage.',
    explanation: 'Rxc8+! Desperado tactic - trade the doomed rook for maximum value.',
    frequency: 'low',
  },

  // ATTRACTION (advanced motif)
  {
    id: '1800-attraction-1',
    name: 'King Attraction',
    fen: 'r1bq1rk1/ppp2ppp/2n5/3pPb2/1b1Pn3/2N2N2/PPPBQPPP/R3KB1R w KQ - 0 1',
    solution: 'Qh5',
    solutionSquare: 'h5',
    motif: 'attraction',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Lure the king to a vulnerable square.',
    explanation: 'Qh5 threatens Qxh7#, forcing the king to h8 where it&apos;s vulnerable.',
    frequency: 'low',
  },

  // Additional GREEK GIFT patterns
  {
    id: '1800-greek-2',
    name: 'Greek Gift Variation',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3p1b2/1b1P4/2NBPN2/PPP2PPP/R1BQ1RK1 w - - 0 1',
    solution: 'Bxh7+',
    solutionSquare: 'h7',
    motif: 'greek-gift',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Classic bishop sacrifice.',
    explanation: 'Bxh7+! Kxh7 Ng5+ Kg6/Kg8 Qg4/Qd3 with winning attack!',
    frequency: 'medium',
  },
  {
    id: '1800-greek-3',
    name: 'Greek Gift Defense',
    fen: 'r1bq1rk1/ppp1nppp/2n5/3p4/1b1P1B2/2NBPN2/PPP2PPP/R2QK2R w KQ - 0 1',
    solution: 'Bxh7+',
    solutionSquare: 'h7',
    motif: 'greek-gift',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Even with defender, sacrifice works.',
    explanation: 'Bxh7+! works despite Ne7 defense. Pattern recognition essential!',
    frequency: 'medium',
  },

  // Additional ZWISCHENZUG patterns
  {
    id: '1800-zwischenzug-2',
    name: 'Counter-Zwischenzug',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'zwischenzug',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Create intermediate threat.',
    explanation: 'Nxd5! Before dealing with b4 bishop, create bigger threat!',
    frequency: 'low',
  },
  {
    id: '1800-zwischenzug-3',
    name: 'Check Zwischenzug',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2NBPN2/PPP2PPP/R1BQK2R b KQ - 0 1',
    solution: 'Nxe4',
    solutionSquare: 'e4',
    motif: 'zwischenzug',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Interpose with check threat.',
    explanation: 'Nxe4! threatens discovered check before bishop retreats.',
    frequency: 'low',
  },

  // Additional DESPERADO patterns
  {
    id: '1800-desperado-2',
    name: 'Desperado Bishop',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'desperado',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Bishop is attacked - go down fighting.',
    explanation: 'Bxf7+! Desperado move. If piece must be lost, maximize damage!',
    frequency: 'low',
  },
  {
    id: '1800-desperado-3',
    name: 'Desperado Queen',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1QN2/PPP2PPP/R1B1KB1R w KQ - 0 1',
    solution: 'Qxf3',
    solutionSquare: 'f3',
    motif: 'desperado',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Queen under attack - grab material.',
    explanation: 'Qxf3! Queen going down - take as much as possible first!',
    frequency: 'low',
  },

  // Complex FORKS
  {
    id: '1800-fork-1',
    name: 'Knight Fork Combo',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'fork',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Centralize with threats.',
    explanation: 'Nd5 forks multiple pieces and controls center. Octopus knight!',
    frequency: 'high',
  },
  {
    id: '1800-fork-2',
    name: 'Queen Fork Mastery',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 b kq - 0 1',
    solution: 'Nd4',
    solutionSquare: 'd4',
    motif: 'fork',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Fork with multiple threats.',
    explanation: 'Nd4! threatens Nf3+, Nxc4, and Nxe2. Multi-threat fork!',
    frequency: 'high',
  },

  // CLEARANCE tactics
  {
    id: '1800-clearance-1',
    name: 'Line Clearance',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P1B2/2N2N2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'exf6',
    solutionSquare: 'f6',
    motif: 'clearance',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Clear the e-file.',
    explanation: 'exf6! clears e5 for rook invasion. Clearance enables attack!',
    frequency: 'low',
  },
  {
    id: '1800-clearance-2',
    name: 'Diagonal Clearance',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2NBPN2/PPP2PPP/R1BQK2R w KQ - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'clearance',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Clear diagonal for bishop.',
    explanation: 'Nxd5 clears c4 diagonal. Opening lines is key!',
    frequency: 'low',
  },

  // SMOTHERED MATE threats
  {
    id: '1800-smothered-1',
    name: 'Smothered Mate Pattern',
    fen: 'r1bq1rk1/ppp2Npp/2n5/3pPb2/1b1P4/2N1B3/PPP2PPP/R2QKB1R b KQ - 0 1',
    solution: 'Qg4',
    solutionSquare: 'g4',
    motif: 'smothered-mate',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Set up smothered mate threat.',
    explanation: 'Qg4 threatens Qg1+ leading to smothered mate!',
    frequency: 'low',
  },
  {
    id: '1800-smothered-2',
    name: 'Smothered Mate Defense',
    fen: 'r1bq1r1k/ppp2Npp/2n5/3pPb2/1b1P4/2N1B3/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Nf6+',
    solutionSquare: 'f6',
    motif: 'smothered-mate',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Force king to corner.',
    explanation: 'Nf6+! Kg7 Nxd5 and king escapes but material won.',
    frequency: 'low',
  },

  // Complex DEFLECTION
  {
    id: '1800-deflection-1',
    name: 'Advanced Deflection',
    fen: 'r2q1rk1/ppp2ppp/2n2n2/3pPb2/1b1P1B2/2N2N2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Bxc6',
    solutionSquare: 'c6',
    motif: 'deflection',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Deflect the knight from defense.',
    explanation: 'Bxc6! bxc6 and f7 is weak. Deflection exposes weaknesses!',
    frequency: 'high',
  },
  {
    id: '1800-deflection-2',
    name: 'Queen Deflection Combo',
    fen: 'r2q1rk1/ppp2ppp/2n5/3pPb2/1b1P1B2/2N1QN2/PPP2PPP/R3KB1R w KQ - 0 1',
    solution: 'Qg3',
    solutionSquare: 'g3',
    motif: 'deflection',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Deflect defender of h7.',
    explanation: 'Qg3! threatens Qxg7#, deflecting defenders.',
    frequency: 'high',
  },

  // ATTRACTION patterns
  {
    id: '1800-attraction-2',
    name: 'Rook Attraction',
    fen: 'r2q1rk1/ppp2ppp/2n5/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Nh4',
    solutionSquare: 'h4',
    motif: 'attraction',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Lure king forward.',
    explanation: 'Nh4! threatens Nf5, attracting king to dangerous square.',
    frequency: 'low',
  },

  // Additional complex PINS
  {
    id: '1800-pin-1',
    name: 'Pin Exploitation Master',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Ng5',
    solutionSquare: 'g5',
    motif: 'pin',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Exploit the pinned f7 pawn.',
    explanation: 'Ng5 attacks f7 twice, exploiting the pin. Multi-attack tactics!',
    frequency: 'high',
  },

  // BATCH 2: Expert-level patterns (21-40)
  {
    id: '1800-greek-4',
    name: 'Greek Gift Refutation',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3p1b2/1b1P4/2NBPN2/PPP2PPP/R1BQK2R w KQ - 0 1',
    solution: 'Bxh7+',
    solutionSquare: 'h7',
    motif: 'greek-gift',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Classic bishop sac despite complications.',
    explanation: 'Bxh7+! works even with defense. Calculate all variations deeply!',
    frequency: 'medium',
  },
  {
    id: '1800-zwischenzug-4',
    name: 'Quiet Zwischenzug',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Qd3',
    solutionSquare: 'd3',
    motif: 'zwischenzug',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Quiet intermediate move threatens mate.',
    explanation: 'Qd3! threatens Qh7# before dealing with threats. Silent but deadly!',
    frequency: 'low',
  },
  {
    id: '1800-desperado-4',
    name: 'Knight Desperado',
    fen: 'r1bq1rk1/ppp2ppp/2n5/3pPb2/1b1Pn3/2N1BN2/PPP2PPP/R2QKB1R b KQ - 0 1',
    solution: 'Nxf2',
    solutionSquare: 'f2',
    motif: 'desperado',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Knight is doomed - strike first.',
    explanation: 'Nxf2! Desperado captures before being eliminated. Maximum damage!',
    frequency: 'low',
  },
  {
    id: '1800-attraction-3',
    name: 'Queen Attraction Pattern',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPPQ1PPP/R3KB1R w KQ - 0 1',
    solution: 'Qh6',
    solutionSquare: 'h6',
    motif: 'attraction',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Lure pieces to vulnerable squares.',
    explanation: 'Qh6! threatens Ng5 forcing king to exposed squares. Attraction wins!',
    frequency: 'low',
  },
  {
    id: '1800-fork-2',
    name: 'Complex Fork Setup',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'fork',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Multi-piece fork after capture.',
    explanation: 'Nxd5! forks queen and c6 knight. Calculate all responses!',
    frequency: 'high',
  },
  {
    id: '1800-skewer-1',
    name: 'Skewer Chain',
    fen: '2kr4/ppp2ppp/2n5/3q4/3P4/2Q5/PPP2PPP/2KR4 w - - 0 1',
    solution: 'Qc8+',
    solutionSquare: 'c8',
    motif: 'skewer',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Multiple skewers in sequence.',
    explanation: 'Qc8+! forces trades leading to material gain. Chain reactions!',
    frequency: 'medium',
  },
  {
    id: '1800-clearance-1',
    name: 'Clearance for Mate',
    fen: 'r1bq1rk1/ppp2ppp/2n5/3pPb2/1b1Pn3/2N1BN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'clearance',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Clear the path for decisive attack.',
    explanation: 'Nxd5! clears e-file for crushing attack. Clearance leads to mate!',
    frequency: 'medium',
  },
  {
    id: '1800-interference-1',
    name: 'Block the Defense',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'interference',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Interfere with coordination.',
    explanation: 'Nd5! blocks defensive lines. Interference destroys coordination!',
    frequency: 'low',
  },
  {
    id: '1800-deflection-1',
    name: 'Deflection Sacrifice',
    fen: 'r2q1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Rxc6',
    solutionSquare: 'c6',
    motif: 'deflection',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Sacrifice to deflect defender.',
    explanation: 'Rxc6! deflects defense of critical square. Sacrifices deflect!',
    frequency: 'high',
  },
  {
    id: '1800-pin-2',
    name: 'Breaking the Pin',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b KQkq - 0 1',
    solution: 'Nd4',
    solutionSquare: 'd4',
    motif: 'pin',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Counter-pin tactics.',
    explanation: 'Nd4! creates counter-pin. When pinned, create counter-threats!',
    frequency: 'high',
  },
  {
    id: '1800-discovered-1',
    name: 'Discovered Check Master',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'discovered-attack',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Discover with maximum effect.',
    explanation: 'Nxd5! discovers attack while capturing. Double power moves!',
    frequency: 'very-high',
  },
  {
    id: '1800-removing-1',
    name: 'Remove Key Piece',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'removing-defender',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Remove the keystone piece.',
    explanation: 'Bxf7+! removes defender of multiple pieces. Cascade effects!',
    frequency: 'high',
  },
  {
    id: '1800-trapped-1',
    name: 'Trap the Major Piece',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b KQkq - 0 1',
    solution: 'Qa5',
    solutionSquare: 'a5',
    motif: 'trapped-piece',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Queen has no good squares.',
    explanation: 'Qa5! threatens bishop, and white queen gets trapped. Piece traps!',
    frequency: 'medium',
  },
  {
    id: '1800-double-1',
    name: 'Double Attack Complex',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Qa4',
    solutionSquare: 'a4',
    motif: 'double-attack',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Attack two critical pieces.',
    explanation: 'Qa4! double attacks c6 knight and b4 bishop. Multiple threats!',
    frequency: 'high',
  },
  {
    id: '1800-greek-5',
    name: 'Greek Gift Defense Test',
    fen: 'r1bq1rk1/ppp1nppp/2n5/3p1b2/1b1P1B2/2NBPN2/PPP2PPP/R2QK2R w KQ - 0 1',
    solution: 'Bxh7+',
    solutionSquare: 'h7',
    motif: 'greek-gift',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Even with Ne7, it works.',
    explanation: 'Bxh7+! Greek Gift works despite defender. Deep calculation needed!',
    frequency: 'medium',
  },
  {
    id: '1800-zwischenzug-5',
    name: 'Counter-Threat Zwischenzug',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R b KQ - 0 1',
    solution: 'Nxd4',
    solutionSquare: 'd4',
    motif: 'zwischenzug',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Create bigger threat first.',
    explanation: 'Nxd4! intermediate capture threatens queen. Tempo matters!',
    frequency: 'low',
  },
  {
    id: '1800-desperado-5',
    name: 'Rook Desperado Complex',
    fen: 'r2q1rk1/ppp2ppp/2n5/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Rxb4',
    solutionSquare: 'b4',
    motif: 'desperado',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Going down - take material.',
    explanation: 'Rxb4! Rook lost anyway - maximize damage first. Desperado mindset!',
    frequency: 'low',
  },
  {
    id: '1800-attraction-4',
    name: 'King Attraction Mate',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPPQ1PPP/R3KB1R w KQ - 0 1',
    solution: 'Qh6',
    solutionSquare: 'h6',
    motif: 'attraction',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Force king to weak square.',
    explanation: 'Qh6! threatens mate, forcing king forward. Attraction to mate!',
    frequency: 'low',
  },
  {
    id: '1800-fork-3',
    name: 'Royal Fork Advanced',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R b KQ - 0 1',
    solution: 'Ne4',
    solutionSquare: 'e4',
    motif: 'fork',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Fork with multiple threats.',
    explanation: 'Ne4! forks queen and c3 knight with tempo. Knights dominate!',
    frequency: 'high',
  },
  {
    id: '1800-skewer-2',
    name: 'Diagonal Skewer',
    fen: 'r1bq1rk1/ppp2ppp/2n5/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Bb6',
    solutionSquare: 'b6',
    motif: 'skewer',
    eloRating: 1800,
    timeLimit: 4,
    hint: 'Skewer on the diagonal.',
    explanation: 'Bb6! skewers queen and back rank. Diagonal power!',
    frequency: 'medium',
  },
];

/**
 * ===== ELO 2000+: MASTER DRILLS =====
 * Focus: Deep calculation, quiet moves, complex sacrifices
 * Time Limit: 3 seconds (!!)
 * Only for players who have mastered all previous levels
 */

export const DRILLS_2000: TacticalDrill[] = [
  // Complex multi-move combinations
  {
    id: '2000-complex-1',
    name: 'Quiet Killer Move',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3p4/3P1B2/2N1PN2/PPP1QPPP/R3K2R w KQ - 0 1',
    solution: 'Qd2',
    solutionSquare: 'd2',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'A quiet move sets up unstoppable threats.',
    explanation: 'Qd2! threatens Bh6 and Qg5 with overwhelming attack. Quiet moves kill!',
    frequency: 'low',
  },
  {
    id: '2000-complex-2',
    name: 'Interference Tactic',
    fen: 'r2qr1k1/ppp2ppp/2n5/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'interference',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Cut the connection between defenders.',
    explanation: "Nd5! interferes with the c6 knight's defense. Advanced geometry!",
    frequency: 'low',
  },
  {
    id: '2000-complex-3',
    name: 'Clearance Sacrifice',
    fen: 'r1bq1rk1/pp3ppp/2n1pn2/3p4/1b1P1B2/2N1PN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Bxf6',
    solutionSquare: 'f6',
    motif: 'clearance',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Clear the path for your pieces.',
    explanation: 'Bxf6 clears the f-file and opens lines for devastating attack.',
    frequency: 'low',
  },

  // Additional quiet moves
  {
    id: '2000-complex-4',
    name: 'Prophylactic Master Move',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3p4/3P1B2/2N1PN2/PPP1QPPP/R3K2R w KQ - 0 1',
    solution: 'Rd1',
    solutionSquare: 'd1',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Control key square quietly.',
    explanation: 'Rd1! prevents ...Nd4 and prepares central domination. Mastery!',
    frequency: 'low',
  },
  {
    id: '2000-complex-5',
    name: 'Positional Zugzwang',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3p4/1b1P1B2/2N1PN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'h3',
    solutionSquare: 'h3',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Quiet pawn move creates threats.',
    explanation: 'h3! prepares g4 advance, creating mating attack. Quiet but deadly!',
    frequency: 'low',
  },

  // Additional INTERFERENCE patterns
  {
    id: '2000-interference-1',
    name: 'Knight Interference',
    fen: 'r2qr1k1/ppp2ppp/2n5/3pPb2/1b1P1B2/2N2N2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'interference',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Block the connection.',
    explanation: 'Nd5! interferes with rook and bishop coordination. Geometric mastery!',
    frequency: 'low',
  },
  {
    id: '2000-interference-2',
    name: 'Bishop Interference',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P4/2N1BN2/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Bd4',
    solutionSquare: 'd4',
    motif: 'interference',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Cut enemy lines.',
    explanation: 'Bd4! blocks queen and rook coordination. Interference wins!',
    frequency: 'low',
  },

  // Additional CLEARANCE patterns
  {
    id: '2000-clearance-1',
    name: 'Rook Clearance',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N1RN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Re1',
    solutionSquare: 'e1',
    motif: 'clearance',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Clear for bishop invasion.',
    explanation: 'Re1 clears e3 for Bd4. Line clearance opens possibilities!',
    frequency: 'low',
  },
  {
    id: '2000-clearance-2',
    name: 'Queen Clearance',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N1PN2/PPP1Q1PP/R3KB1R w KQ - 0 1',
    solution: 'Qd3',
    solutionSquare: 'd3',
    motif: 'clearance',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Clear e2 for rook.',
    explanation: 'Qd3 clears e-file for rook domination. Coordination is key!',
    frequency: 'low',
  },

  // Complex multi-move COMBINATIONS
  {
    id: '2000-combo-1',
    name: '3-Move Combination',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P1B2/2NBPN2/PPP2PPP/R2QK2R w KQ - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Start forcing sequence.',
    explanation: 'Bxf7+! Kxf7 Ng5+ Kg8 Qh5 wins. Calculate precisely!',
    frequency: 'low',
  },
  {
    id: '2000-combo-2',
    name: 'Forced Win Sequence',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P1B2/2N1PN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'exf6',
    solutionSquare: 'f6',
    motif: 'clearance',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Open lines forcefully.',
    explanation: 'exf6! Qxf6 Bxc6 and material advantage. Forcing moves!',
    frequency: 'low',
  },

  // Advanced FORK patterns
  {
    id: '2000-fork-1',
    name: 'Geometric Fork',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N2N2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'fork',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Central fork with tempo.',
    explanation: 'Nd5! forks multiple pieces while controlling center. Dominance!',
    frequency: 'high',
  },
  {
    id: '2000-fork-2',
    name: 'Queen Fork Geometry',
    fen: 'r2qr1k1/ppp2ppp/2n1bn2/3pPb2/1b1P4/2N1BN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Qa6',
    solutionSquare: 'a6',
    motif: 'fork',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Long-range fork.',
    explanation: 'Qa6! attacks bishop and threatens back rank. Geometric vision!',
    frequency: 'high',
  },

  // Advanced DEFLECTION
  {
    id: '2000-deflection-1',
    name: 'Multi-Piece Deflection',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N1PN2/PPP1Q1PP/R3KB1R w KQ - 0 1',
    solution: 'Bxc6',
    solutionSquare: 'c6',
    motif: 'deflection',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Deflect two defenders.',
    explanation: 'Bxc6! deflects from f7 and d4. Multiple deflections win!',
    frequency: 'high',
  },
  {
    id: '2000-deflection-2',
    name: 'Queen Deflection Mastery',
    fen: 'r2q1rk1/ppp2ppp/2n5/3pPb2/1b1P1B2/2N1QN2/PPP2PPP/R3KB1R w KQ - 0 1',
    solution: 'Qe4',
    solutionSquare: 'e4',
    motif: 'deflection',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Deflect from multiple squares.',
    explanation: 'Qe4! threatens Qxh7# and Qxa8. Multi-threat deflection!',
    frequency: 'high',
  },

  // Advanced ATTRACTION
  {
    id: '2000-attraction-1',
    name: 'King Attraction Sequence',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P1B2/2NBPN2/PPP1QPPP/R3K2R w KQ - 0 1',
    solution: 'Bh6',
    solutionSquare: 'h6',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Lure king to mating net.',
    explanation: 'Bh6! forces gxh6 and king exposed. Attraction to doom!',
    frequency: 'low',
  },
  {
    id: '2000-attraction-2',
    name: 'Piece Attraction',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N1PN2/PPP1Q1PP/R3KB1R w KQ - 0 1',
    solution: 'Nh4',
    solutionSquare: 'h4',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Lure defender away.',
    explanation: 'Nh4! attracts bishop from key diagonal. Positional mastery!',
    frequency: 'low',
  },

  // Advanced ZWISCHENZUG
  {
    id: '2000-zwischenzug-1',
    name: 'Double Zwischenzug',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'zwischenzug',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Two in-between moves.',
    explanation: 'Nxd5! threatens Nc7+ before recapture. Double tempo!',
    frequency: 'low',
  },
  {
    id: '2000-zwischenzug-2',
    name: 'Check Zwischenzug Master',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2NBPN2/PPP1QPPP/R3KB1R b KQ - 0 1',
    solution: 'Nxe4',
    solutionSquare: 'e4',
    motif: 'zwischenzug',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Intermediate check threat.',
    explanation: 'Nxe4! threatens Nf2+ before dealing with threats. Tempo is everything!',
    frequency: 'low',
  },

  // Advanced SMOTHERED MATE
  {
    id: '2000-smothered-1',
    name: 'Smothered Mate Sequence',
    fen: 'r1bq1r1k/ppp2Npp/2n5/3pPb2/1b1P4/2N1B3/PPP2PPP/R2QKB1R w KQ - 0 1',
    solution: 'Qg5',
    solutionSquare: 'g5',
    motif: 'smothered-mate',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Set up the smothered mate pattern.',
    explanation: 'Qg5! threatens Qg7# and forces defensive moves leading to smother. Mastery!',
    frequency: 'low',
  },

  // BATCH 2: Master-level deep tactics (21-40)
  {
    id: '2000-greek-1',
    name: 'Greek Gift Complex',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3p1b2/1b1P1B2/2NBPN2/PPP1QPPP/R3K2R w KQ - 0 1',
    solution: 'Bxh7+',
    solutionSquare: 'h7',
    motif: 'greek-gift',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Calculate all variations.',
    explanation: 'Bxh7+! Kxh7 Ng5+ Kg8 Qh5 wins. Greek Gift at master level!',
    frequency: 'medium',
  },
  {
    id: '2000-desperado-1',
    name: 'Master Desperado',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N1RN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Rxe6',
    solutionSquare: 'e6',
    motif: 'desperado',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Rook doomed - maximize.',
    explanation: 'Rxe6! fxe6 and rook gets maximum value. Desperado excellence!',
    frequency: 'low',
  },
  {
    id: '2000-pin-1',
    name: 'Pin Exploitation Expert',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP1QPPP/R1B1K2R w KQ - 0 1',
    solution: 'Ng5',
    solutionSquare: 'g5',
    motif: 'pin',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Exploit pinned pieces.',
    explanation: 'Ng5! attacks f7 and h7. Pinned pieces are sitting ducks!',
    frequency: 'high',
  },
  {
    id: '2000-skewer-1',
    name: 'Master Skewer',
    fen: '2kr4/ppp2ppp/2n5/3q1b2/3P4/2Q5/PPP2PPP/2KR4 w - - 0 1',
    solution: 'Qc8+',
    solutionSquare: 'c8',
    motif: 'skewer',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Force trade and win.',
    explanation: 'Qc8+! Kxc8 Rxd5. Skewer leads to material advantage!',
    frequency: 'medium',
  },
  {
    id: '2000-discovered-1',
    name: 'Discovered Check Mastery',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'discovered-attack',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Discover with check.',
    explanation: 'Nxd5! discovers bishop attack on f5. Discovery at master level!',
    frequency: 'very-high',
  },
  {
    id: '2000-removing-1',
    name: 'Remove Defender Master',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP1QPPP/R1B1K2R w KQ - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'removing-defender',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Remove key piece.',
    explanation: 'Bxf7+! Kxf7 and position collapses. Remove the cornerstone!',
    frequency: 'high',
  },
  {
    id: '2000-trapped-1',
    name: 'Trap Major Piece',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP1QPPP/R1B1K2R b KQ - 0 1',
    solution: 'Qa5',
    solutionSquare: 'a5',
    motif: 'trapped-piece',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Queen trapped.',
    explanation: 'Qa5! and white queen has no good squares. Piece entrapment!',
    frequency: 'medium',
  },
  {
    id: '2000-double-1',
    name: 'Double Attack Supreme',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Qa6',
    solutionSquare: 'a6',
    motif: 'double-attack',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Attack two pieces.',
    explanation: 'Qa6! attacks c6 and b4. Double threat at highest level!',
    frequency: 'high',
  },
  {
    id: '2000-interference-3',
    name: 'Interference Master',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P4/2N1BN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Nd5',
    solutionSquare: 'd5',
    motif: 'interference',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Block coordination.',
    explanation: 'Nd5! interferes with all defensive lines. Coordination destroyed!',
    frequency: 'low',
  },
  {
    id: '2000-clearance-3',
    name: 'Clearance Master',
    fen: 'r1bq1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N1RN2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Rxe6',
    solutionSquare: 'e6',
    motif: 'clearance',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Clear for attack.',
    explanation: 'Rxe6! fxe6 opens f-file for devastating attack. Clearance mastery!',
    frequency: 'medium',
  },
  {
    id: '2000-combo-3',
    name: 'Four-Move Combo',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P1B2/2NBPN2/PPP1QPPP/R3K2R w KQ - 0 1',
    solution: 'Bxf7+',
    solutionSquare: 'f7',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Four-move forced win.',
    explanation: 'Bxf7+! Kxf7 Ng5+ Kg8 Qh5 threatens mate. Deep calculation!',
    frequency: 'low',
  },
  {
    id: '2000-quiet-1',
    name: 'Quiet Move Mastery',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N1PN2/PPP1Q1PP/R3KB1R w KQ - 0 1',
    solution: 'Kf1',
    solutionSquare: 'f1',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Quiet king move.',
    explanation: 'Kf1! prepares Re1 and dominates e-file. Prophylaxis at its finest!',
    frequency: 'low',
  },
  {
    id: '2000-fork-3',
    name: 'Master Fork Pattern',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N2N2/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Nxd5',
    solutionSquare: 'd5',
    motif: 'fork',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Fork with tempo.',
    explanation: 'Nxd5! forks queen and c6. Geometric perfection!',
    frequency: 'high',
  },
  {
    id: '2000-deflection-3',
    name: 'Deflection Supreme',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N1PN2/PPP1Q1PP/R3KB1R w KQ - 0 1',
    solution: 'Bxc6',
    solutionSquare: 'c6',
    motif: 'deflection',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Deflect multiple defenders.',
    explanation: 'Bxc6! deflects from d4 and f7. Multi-deflection wins!',
    frequency: 'high',
  },
  {
    id: '2000-attraction-3',
    name: 'Attraction Complex',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P1B2/2NBPN2/PPP1QPPP/R3K2R w KQ - 0 1',
    solution: 'Bh6',
    solutionSquare: 'h6',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Lure king to danger.',
    explanation: 'Bh6! forces gxh6 exposing king. Attraction to mate threats!',
    frequency: 'low',
  },
  {
    id: '2000-zwischenzug-3',
    name: 'Zwischenzug Chain',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3pPb2/1b1P4/2N1BN2/PPP1QPPP/R3KB1R b KQ - 0 1',
    solution: 'Nxd4',
    solutionSquare: 'd4',
    motif: 'zwischenzug',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Two intermediate moves.',
    explanation: 'Nxd4! threatens queen with check threat. In-between mastery!',
    frequency: 'low',
  },
  {
    id: '2000-greek-2',
    name: 'Greek Gift Variation',
    fen: 'r1bq1rk1/ppp1nppp/2n5/3p1b2/1b1P1B2/2NBPN2/PPP1QPPP/R3K2R w KQ - 0 1',
    solution: 'Bxh7+',
    solutionSquare: 'h7',
    motif: 'greek-gift',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Despite Ne7 defense.',
    explanation: 'Bxh7+! works even with defender. Calculate all lines!',
    frequency: 'medium',
  },
  {
    id: '2000-pin-2',
    name: 'Pin Breaking Mastery',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP1QPPP/R1B1K2R b KQ - 0 1',
    solution: 'Nd4',
    solutionSquare: 'd4',
    motif: 'pin',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Counter-pin.',
    explanation: 'Nd4! creates counter-pin on white knight. When pinned, counter-attack!',
    frequency: 'high',
  },
  {
    id: '2000-smothered-2',
    name: 'Smothered Mate Setup',
    fen: 'r1bq1r1k/ppp2Npp/2n5/3pPb2/1b1P4/2N1B3/PPP1QPPP/R3KB1R w KQ - 0 1',
    solution: 'Qh5',
    solutionSquare: 'h5',
    motif: 'smothered-mate',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Threaten smothered mate.',
    explanation: 'Qh5! threatens Qg7#. Forces defensive errors leading to smother!',
    frequency: 'low',
  },
  {
    id: '2000-complex-6',
    name: 'Positional Masterpiece',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pPb2/1b1P1B2/2N1PN2/PPP1Q1PP/R3KB1R w KQ - 0 1',
    solution: 'g4',
    solutionSquare: 'g4',
    motif: 'attraction',
    eloRating: 2000,
    timeLimit: 3,
    hint: 'Quiet pawn advance.',
    explanation: 'g4! prepares kingside storm. Silent moves create thunderstorms!',
    frequency: 'low',
  },
];

/**
 * ALL DRILLS BY ELO
 */
export const DRILLS_BY_ELO: Record<ELORating, TacticalDrill[]> = {
  800: DRILLS_800,
  1000: DRILLS_1200, // Reuse 1200 for gradual progression
  1200: DRILLS_1200,
  1400: DRILLS_1400,
  1600: DRILLS_1400, // Reuse 1400 - focus is on speed mastery
  1800: DRILLS_1800,
  2000: DRILLS_2000,
};

export const ALL_DRILLS: TacticalDrill[] = [
  ...DRILLS_800,
  ...DRILLS_1200,
  ...DRILLS_1400,
  ...DRILLS_1800,
  ...DRILLS_2000,
];

/**
 * DRILLS BY MOTIF (for targeted training)
 */
export const DRILLS_BY_MOTIF: Partial<Record<TacticalMotif, TacticalDrill[]>> = {
  fork: ALL_DRILLS.filter(d => d.motif === 'fork'),
  'hanging-piece': ALL_DRILLS.filter(d => d.motif === 'hanging-piece'),
  pin: ALL_DRILLS.filter(d => d.motif === 'pin'),
  'discovered-attack': ALL_DRILLS.filter(d => d.motif === 'discovered-attack'),
  skewer: ALL_DRILLS.filter(d => d.motif === 'skewer'),
  'back-rank-mate': ALL_DRILLS.filter(d => d.motif === 'back-rank-mate'),
  deflection: ALL_DRILLS.filter(d => d.motif === 'deflection'),
  'x-ray': ALL_DRILLS.filter(d => d.motif === 'x-ray'),
  'trapped-piece': ALL_DRILLS.filter(d => d.motif === 'trapped-piece'),
  'greek-gift': ALL_DRILLS.filter(d => d.motif === 'greek-gift'),
  zwischenzug: ALL_DRILLS.filter(d => d.motif === 'zwischenzug'),
};

/**
 * Get drills for specific ELO rating
 */
export function getDrillsByELO(elo: ELORating): TacticalDrill[] {
  return DRILLS_BY_ELO[elo] || DRILLS_800;
}

/**
 * Get drills by motif
 */
export function getDrillsByMotif(motif: TacticalMotif): TacticalDrill[] {
  return DRILLS_BY_MOTIF[motif] || [];
}

/**
 * Get "Big 4" drills (highest frequency tactics)
 */
export function getBig4Drills(elo: ELORating = 800): TacticalDrill[] {
  const allDrills = getDrillsByELO(elo);
  return allDrills.filter(
    d =>
      d.motif === 'fork' ||
      d.motif === 'hanging-piece' ||
      d.motif === 'discovered-attack' ||
      d.motif === 'pin'
  );
}

/**
 * Get next ELO tier
 */
export function getNextELOTier(currentELO: ELORating): ELORating | null {
  const tiers: ELORating[] = [800, 1000, 1200, 1400, 1600, 1800, 2000];
  const currentIndex = tiers.indexOf(currentELO);
  return currentIndex < tiers.length - 1 ? tiers[currentIndex + 1] : null;
}

/**
 * Get motif display name
 */
export function getMotifDisplayName(motif: TacticalMotif): string {
  const names: Record<TacticalMotif, string> = {
    fork: 'Fork',
    'hanging-piece': 'Hanging Piece',
    pin: 'Pin',
    'discovered-attack': 'Discovered Attack',
    skewer: 'Skewer',
    'back-rank-mate': 'Back Rank Mate',
    'double-attack': 'Double Attack',
    deflection: 'Deflection',
    'x-ray': 'X-Ray Attack',
    'trapped-piece': 'Trapped Piece',
    'removing-defender': 'Removing Defender',
    'greek-gift': 'Greek Gift',
    zwischenzug: 'Zwischenzug',
    desperado: 'Desperado',
    'smothered-mate': 'Smothered Mate',
    attraction: 'Attraction',
    clearance: 'Clearance',
    interference: 'Interference',
  };
  return names[motif] || motif;
}

/**
 * Calculate speed rating based on time used
 * Returns: "flash" | "fast" | "good" | "slow" | "too-slow"
 */
export function calculateSpeedRating(timeLimit: number, timeUsed: number): string {
  const percentage = (timeUsed / timeLimit) * 100;

  if (percentage <= 40) return 'flash'; // Solved in < 40% of time
  if (percentage <= 60) return 'fast'; // Solved in < 60% of time
  if (percentage <= 80) return 'good'; // Solved in < 80% of time
  if (percentage <= 100) return 'slow'; // Solved before timeout
  return 'too-slow'; // Failed to solve
}

/**
 * Check if player can advance to next ELO tier
 * Requirement: 80% accuracy + 70% solved in "fast" or "flash" time
 */
export function canAdvanceToNextTier(
  accuracy: number,
  flashCount: number,
  fastCount: number,
  totalAttempts: number
): boolean {
  const speedPercentage = ((flashCount + fastCount) / totalAttempts) * 100;
  return accuracy >= 80 && speedPercentage >= 70;
}
